-- Create tables for Supabase Production
-- Enable RLS

CREATE TABLE IF NOT EXISTS sections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type VARCHAR(50) NOT NULL,
  title VARCHAR(255) NOT NULL,
  content JSONB NOT NULL DEFAULT '{}',
  "order" INTEGER DEFAULT 0,
  is_visible BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE sections ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS blogs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug VARCHAR(255) UNIQUE NOT NULL,
  title VARCHAR(255) NOT NULL,
  excerpt TEXT,
  content TEXT,
  cover_image VARCHAR(255),
  published_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE blogs ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS media (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  filename VARCHAR(255) NOT NULL,
  url VARCHAR(255) NOT NULL,
  mime_type VARCHAR(100),
  size_bytes BIGINT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE media ENABLE ROW LEVEL SECURITY;

-- Policies

-- Public Read Policies
CREATE POLICY "Public Read Sections" ON sections FOR SELECT USING (true);
CREATE POLICY "Public Read Blogs" ON blogs FOR SELECT USING (true);
CREATE POLICY "Public Read Media" ON media FOR SELECT USING (true);

-- Admin Write Policies (Strict)
-- REPLACE 'YOUR_UUID_HERE' with your actual Supabase User ID
CREATE POLICY "Admin Write Sections" ON sections FOR ALL USING (auth.uid() = 'YOUR_UUID_HERE');
CREATE POLICY "Admin Write Blogs" ON blogs FOR ALL USING (auth.uid() = 'YOUR_UUID_HERE');
CREATE POLICY "Admin Write Media" ON media FOR ALL USING (auth.uid() = 'YOUR_UUID_HERE');

-- Storage Bucket Setup (Conceptual - usually done via UI or API, but can be scripted if extensions enabled)
-- insert into storage.buckets (id, name, public) values ('media', 'media', true);
-- create policy "Public Access" on storage.objects for select using ( bucket_id = 'media' );
-- create policy "Admin Upload" on storage.objects for insert using ( bucket_id = 'media' and auth.uid() = 'YOUR_UUID_HERE' );
